#!/bin/bash

# Echo invoked commands, stop on error
set -xe

# Change to script directory
cd "$(dirname "$(realpath "$0")")";

# Ensure required variables are set
if [[ -z ${CI_COMMIT_REF_NAME} ]]; then
    echo "Error: variable CI_COMMIT_REF_NAME is not set"
    exit 1
fi

# Install dependencies
echo "Installing required build packages..."
pacman -Syu --noconfirm sudo base-devel binutils openssh rust cargo cmake git openssl python libxcb

# Determine the version number we're releasing for
VERSION=$(echo $CI_COMMIT_REF_NAME | cut -c 2-)
VERSION_GIT=$(git describe --long | git describe --long | sed "s/^v//;s/\([^-]*-g\)/r\1/;s/-/./g")
echo "Determined version number: v$VERSION"

# Determine remote URLs and SHA checksums
echo "Getting SHA checksums for remote files..."
URL_SOURCE=https://gitlab.com/timvisee/prs/-/archive/v$VERSION/prs-v$VERSION.tar.gz
SHA_SOURCE=$(curl -sSL "$URL_SOURCE" | sha512sum | cut -d" " -f1)
echo "Source checksum: $SHA_SOURCE ($URL_SOURCE)"

# Update PKGBUILDs
echo "Updating PKGBUILDS with release information..."
sed "s/__PKGVER__/$VERSION/" -i prs/PKGBUILD
sed "s/__PKGVER__/$VERSION_GIT/" -i prs-git/PKGBUILD
sed "s/__SHA512SUM__/$SHA_SOURCE/" -i prs/PKGBUILD

# Prepare for make
mkdir -p /.cargo
chmod -R 777 /.cargo

# Make prs package
cd prs/
echo "Making prs package..."
sudo -u nobody makepkg -c
sudo -u nobody makepkg --printsrcinfo > .SRCINFO
cd ..

# Make prs-git package
cd prs-git/
echo "Making prs-git package..."
sudo -u nobody makepkg -c
sudo -u nobody makepkg --printsrcinfo > .SRCINFO
cd ..

# Set up SSH for publishing
mkdir -p /root/.ssh
cp ./aur.pub /root/.ssh/id_rsa.pub
echo "$AUR_SSH_PRIVATE" > /root/.ssh/id_rsa
echo "Host aur.archlinux.org" >> /root/.ssh/config
echo "  IdentityFile /root/.ssh/aur" >> /root/.ssh/config
echo "  User aur" >> /root/.ssh/config
chmod 600 /root/.ssh/{id_rsa*,config}
eval `ssh-agent -s`
ssh-add /root/.ssh/id_rsa
ssh-keyscan -H aur.archlinux.org >> /root/.ssh/known_hosts
git config --global user.name "timvisee"
git config --global user.email "tim@visee.me"

# Publish prs package (clone AUR repo, commit update, push)
git clone ssh://aur@aur.archlinux.org/prs.git aur-prs
cd aur-prs
cp ../prs/{PKGBUILD,.SRCINFO} ./
git add PKGBUILD .SRCINFO
git commit -m "prs $VERSION"
git push
cd ..

# Publish prs-git package (clone AUR repo, commit update, push)
git clone ssh://aur@aur.archlinux.org/prs-git.git aur-prs-git
cd aur-prs-git
cp ../prs-git/{PKGBUILD,.SRCINFO} ./
git add PKGBUILD .SRCINFO
git commit -m "prs-git $VERSION"
git push
cd ..
